import os
import re
import io
from datetime import datetime, timezone
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image
)
try:
    from reportlab.platypus import HRFlowable
except ImportError:
    from reportlab.platypus.flowables import HRFlowable

from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

# Font registration settings
FONT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../fonts/tex-gyre-termes"))

FONT_NAME = "Helvetica"
FONT_BOLD = "Helvetica-Bold"
FONT_ITALIC = "Helvetica-Oblique"
FONT_BOLD_ITALIC = "Helvetica-BoldOblique"
HAS_CUSTOM_FONT = False

try:
    def get_font_file(base_name):
        for ext in [".ttf", ".otf"]:
            p = os.path.join(FONT_DIR, f"{base_name}{ext}")
            if os.path.exists(p):
                return p
        return None

    regular_path = get_font_file("texgyretermes-regular")
    bold_path = get_font_file("texgyretermes-bold")
    italic_path = get_font_file("texgyretermes-italic")
    bolditalic_path = get_font_file("texgyretermes-bolditalic")

    if regular_path and bold_path and italic_path and bolditalic_path:
        pdfmetrics.registerFont(TTFont("TexGyreTermes", regular_path))
        pdfmetrics.registerFont(TTFont("TexGyreTermes-Bold", bold_path))
        pdfmetrics.registerFont(TTFont("TexGyreTermes-Italic", italic_path))
        pdfmetrics.registerFont(TTFont("TexGyreTermes-BoldItalic", bolditalic_path))
        
        pdfmetrics.registerFontFamily(
            "TexGyreTermes",
            normal="TexGyreTermes",
            bold="TexGyreTermes-Bold",
            italic="TexGyreTermes-Italic",
            boldItalic="TexGyreTermes-BoldItalic"
        )
        FONT_NAME = "TexGyreTermes"
        FONT_BOLD = "TexGyreTermes-Bold"
        FONT_ITALIC = "TexGyreTermes-Italic"
        FONT_BOLD_ITALIC = "TexGyreTermes-BoldItalic"
        HAS_CUSTOM_FONT = True
except Exception as e:
    # If font registration fails, fallback to Helvetica family
    pass

# Custom Paragraph Styles
h2_style = ParagraphStyle(
    "H2Style",
    fontName=FONT_BOLD,
    fontSize=13,
    leading=17,
    textColor=HexColor("#A31D1D"),
    spaceBefore=12,
    spaceAfter=6,
    keepWithNext=True
)

h3_style = ParagraphStyle(
    "H3Style",
    fontName=FONT_BOLD,
    fontSize=11,
    leading=15,
    textColor=HexColor("#1a1a1a"),
    spaceBefore=8,
    spaceAfter=4,
    keepWithNext=True
)

body_style = ParagraphStyle(
    "BodyStyle",
    fontName=FONT_NAME,
    fontSize=10,
    leading=14,
    textColor=HexColor("#1a1a1a"),
    spaceAfter=8
)

bullet_style = ParagraphStyle(
    "BulletStyle",
    fontName=FONT_NAME,
    fontSize=10,
    leading=14,
    textColor=HexColor("#1a1a1a"),
    leftIndent=14.17,  # 0.5cm = 14.17 points
    firstLineIndent=-10,
    spaceAfter=4
)

numbered_style = ParagraphStyle(
    "NumberedStyle",
    fontName=FONT_NAME,
    fontSize=10,
    leading=14,
    textColor=HexColor("#1a1a1a"),
    leftIndent=20,          # space for number + gap
    firstLineIndent=-12,    # hang the number to the left
    spaceAfter=4
)

class NumberedCanvas(canvas.Canvas):
    """
    Custom canvas that performs two-pass rendering to dynamically compute total page count
    and draw a professional footer and running header on every page.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []
        self.footer_date = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M") + " UTC"
        self.report_type = ""
        self.display_id = ""
        self.patient_name = ""

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        
        self.setFont(FONT_NAME, 8)
        self.setFillColor(HexColor("#666666"))
        
        # Left-aligned footer
        footer_text = f"Generated by HematoX · Educational use only · {self.footer_date}"
        self.drawString(56.69, 34.0, footer_text)
        
        # Right-aligned page number
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(538.58, 34.0, page_str)
        
        # Draw running header on page 2 onwards
        if self._pageNumber > 1:
            m_type = (self.report_type or "cbc").upper()
            if m_type == "COAG":
                m_type = "COAGULATION"
                
            header_left = f"{m_type} REPORT"
            if self.patient_name:
                header_left += f" · Patient: {self.patient_name}"
                
            header_right = f"ID: {self.display_id}" if self.display_id else ""
            
            self.drawString(56.69, 805.0, header_left)
            if header_right:
                self.drawRightString(538.58, 805.0, header_right)
                
            # Draw a thin decorative line under the header at y = 797
            self.setStrokeColor(HexColor("#E5E7EB"))
            self.setLineWidth(0.5)
            self.line(56.69, 797.0, 538.58, 797.0)
            
        self.restoreState()


def convert_md_to_html_tags(text: str) -> str:
    """
    Replaces basic markdown syntaxes (**bold**, *italic*) with HTML tags (<b>, <i>)
    after escaping XML special characters to guarantee correct parsing inside Paragraph.
    """
    # Escape XML characters first to avoid parsing errors
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    
    # Now replace bold **...** or __...__
    text = re.sub(r'\*\*(.*?)\*\*|__(.*?)__', lambda m: f"<b>{m.group(1) or m.group(2)}</b>", text)
    
    # Now replace italic *...* or _..._
    text = re.sub(r'\*(.*?)\*|_(.*?)_', lambda m: f"<i>{m.group(1) or m.group(2)}</i>", text)
    
    # Restore back escaped entities that are required for tags
    text = text.replace("&lt;b&gt;", "<b>").replace("&lt;/b&gt;", "</b>")
    text = text.replace("&lt;i&gt;", "<i>").replace("&lt;/i&gt;", "</i>")
    
    return text


def parse_markdown_to_flowables(markdown_text: str):
    """
    Simple line-by-line parser that converts the markdown output
    into a list of ReportLab Flowable objects.
    Supports headers, horizontal rules, unordered lists (-, *, •),
    and ordered lists (1., 2., 3.).
    """
    flowables = []
    lines = markdown_text.splitlines()
    buffer = []
    
    def flush_buffer():
        if buffer:
            text = " ".join(buffer).strip()
            if text:
                html_text = convert_md_to_html_tags(text)
                flowables.append(Paragraph(html_text, body_style))
            buffer.clear()

    for line in lines:
        line_stripped = line.strip()
        if not line_stripped:
            flush_buffer()
            continue
        
        # Headers
        if line_stripped.startswith("## "):
            flush_buffer()
            heading_text = convert_md_to_html_tags(line_stripped[3:].strip())
            flowables.append(Paragraph(heading_text, h2_style))
        elif line_stripped.startswith("### "):
            flush_buffer()
            heading_text = convert_md_to_html_tags(line_stripped[4:].strip())
            flowables.append(Paragraph(heading_text, h3_style))
        
        # Ordered list (numbered) - must come before bullet detection
        elif re.match(r'^\d+\.\s+', line_stripped):
            flush_buffer()
            # Split number and text
            parts = line_stripped.split('.', 1)
            number = parts[0].strip()
            item_text = parts[1].strip()
            item_html = convert_md_to_html_tags(item_text)
            flowables.append(Paragraph(f"{number}.&nbsp;&nbsp;{item_html}", numbered_style))
        
        # Unordered list (bullet)
        elif line_stripped.startswith("- ") or line_stripped.startswith("* ") or line_stripped.startswith("• "):
            flush_buffer()
            # extract text
            if line_stripped.startswith("- "):
                item_text = line_stripped[2:]
            elif line_stripped.startswith("* "):
                item_text = line_stripped[2:]
            else:
                item_text = line_stripped[2:]
            item_html = convert_md_to_html_tags(item_text.strip())
            flowables.append(Paragraph(f"•&nbsp;&nbsp;{item_html}", bullet_style))
        
        # Horizontal rules
        elif line_stripped in ("---", "***", "___"):
            flush_buffer()
            flowables.append(HRFlowable(
                width="100%",
                thickness=1,
                color=HexColor("#A31D1D"),
                spaceBefore=10,
                spaceAfter=15
            ))
        else:
            buffer.append(line_stripped)
            
    flush_buffer()
    return flowables


router = APIRouter()


class PDFExportRequest(BaseModel):
    markdown: str
    title: str = "HematoX Report"
    patient_name: str = ""
    display_id: str = ""
    module_type: str = ""


@router.post("/pdf")
async def export_pdf(payload: PDFExportRequest):
    try:
        # Create an in-memory bytes buffer
        pdf_buffer = io.BytesIO()
        
        # Document template A4 (595.27 x 841.89)
        # Margins: Top: 2cm (56.69), Bottom: 2.5cm (70.87), Left: 2cm (56.69), Right: 2cm (56.69)
        doc = SimpleDocTemplate(
            pdf_buffer,
            pagesize=A4,
            leftMargin=56.69,
            rightMargin=56.69,
            topMargin=56.69,
            bottomMargin=70.87
        )
        
        story = []
        
        # 1. Header Section Table
        LOGO_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../assets/logo.png"))
        logo_img = ""
        if os.path.exists(LOGO_PATH):
            logo_img = Image(LOGO_PATH, width=56.69, height=56.69)
            
        header_title_style = ParagraphStyle(
            "HeaderTitle",
            fontName=FONT_BOLD,
            fontSize=16,
            leading=20,
            textColor=HexColor("#1a1a1a"),
            alignment=TA_RIGHT
        )
        
        header_id_style = ParagraphStyle(
            "HeaderID",
            fontName=FONT_NAME,
            fontSize=10,
            leading=14,
            textColor=HexColor("#1a1a1a"),
            alignment=TA_RIGHT
        )
        
        m_type = (payload.module_type or "cbc").upper()
        if m_type == "COAG":
            m_type = "COAGULATION"
        header_title_text = f"HematoX - {m_type} Report"

        right_col = [
            Paragraph(header_title_text, header_title_style),
            Spacer(1, 4),
            Paragraph(f"ID: {payload.display_id}" if payload.display_id else "ID: -", header_id_style)
        ]
        if payload.patient_name:
            right_col.append(Spacer(1, 2))
            right_col.append(Paragraph(f"Patient: {payload.patient_name}", header_id_style))
        
        header_table = Table([[logo_img, right_col]], colWidths=[56.69, 425.2])
        header_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
        ]))
        story.append(header_table)
        
        # 2. Horizontal Rule (dark red #A31D1D, 1pt)
        hr = HRFlowable(
            width="100%",
            thickness=1,
            color=HexColor("#A31D1D"),
            spaceBefore=10,
            spaceAfter=10
        )
        story.append(hr)
        
        # 3. Patient Line
        patient_style = ParagraphStyle(
            "PatientStyle",
            fontName=FONT_ITALIC,
            fontSize=10,
            leading=14,
            textColor=HexColor("#1a1a1a")
        )
        
        date_style = ParagraphStyle(
            "DateStyle",
            fontName=FONT_NAME,
            fontSize=10,
            leading=14,
            textColor=HexColor("#1a1a1a"),
            alignment=TA_RIGHT
        )
        
        patient_text = f"Patient: {payload.patient_name}" if payload.patient_name else ""
        utc_now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M") + " UTC"
        date_text = f"Date: {utc_now_str}"
        
        metadata_table = Table(
            [[Paragraph(patient_text, patient_style), Paragraph(date_text, date_style)]],
            colWidths=[240.94, 240.94]
        )
        metadata_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
        ]))
        story.append(metadata_table)
        story.append(Spacer(1, 15))
        
        # 4. Report Title: 16pt bold, dark red
        title_style = ParagraphStyle(
            "ReportTitleStyle",
            fontName=FONT_BOLD,
            fontSize=16,
            leading=20,
            textColor=HexColor("#A31D1D"),
            spaceAfter=15
        )
        story.append(Paragraph(payload.title, title_style))
        
        # 5. Parse body markdown
        body_flowables = parse_markdown_to_flowables(payload.markdown)
        story.extend(body_flowables)
        
        # Build the PDF
        # Build the PDF using a custom subclass of NumberedCanvas containing the payload context
        class CustomNumberedCanvas(NumberedCanvas):
            def __init__(self, *args, **kwargs):
                super().__init__(*args, **kwargs)
                self.report_type = payload.module_type
                self.display_id = payload.display_id
                self.patient_name = payload.patient_name

        doc.build(story, canvasmaker=CustomNumberedCanvas)
        
        # Rewind buffer
        pdf_buffer.seek(0)
        pdf_bytes = pdf_buffer.getvalue()
        
        # Filename: Content-Disposition: attachment; filename="hematox_{display_id or 'report'}_{date}.pdf"
        file_date = datetime.now(timezone.utc).strftime("%Y%m%d")
        disp_id = payload.display_id if payload.display_id else "report"
        filename = f"hematox_{disp_id}_{file_date}.pdf"
        
        return StreamingResponse(
            iter([pdf_bytes]),
            media_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'}
        )
        
    except Exception as e:
        raise HTTPException(
            status_code=503,
            detail=f"PDF generation failed: {str(e)}"
        )
