import React, { createContext, useState, useEffect, useContext } from 'react';

const LanguageContext = createContext();

const dictionary = {
  en: {
    // common/general
    cancel: "Cancel",
    confirm: "Confirm",
    saveChanges: "Save Changes",
    goBack: "Go Back",
    areYouSure: "Are you sure?",
    patientLabel: "Patient",
    
    // common/sidebar
    dashboard: "Dashboard",
    cbc: "CBC",
    coagulation: "Coagulation",
    rotem: "ROTEM",
    casebook: "Casebook",
    chat: "Chat",
    settings: "Settings",
    patientName: "Patient Name (optional — for report labeling only)",
    patientContext: "Patient Context",
    age: "Age",
    sex: "Sex",
    unspecified: "Unspecified",
    male: "Male",
    female: "Female",
    analyzing: "Analyzing...",
    goToSettings: "Go to Settings",
    saveToCasebook: "Save to Casebook",
    savedToCasebook: "Saved to Casebook",
    
    // home page / dashboard
    clinicalAnalysis: "Clinical Analysis",
    selectModule: "Select a diagnostic module to begin structured interpretation.",
    cbcInterpreter: "CBC Interpreter",
    cbcInterpreterDesc: "Interpret complete blood count values including red cell indices, WBC differential, and platelet parameters.",
    coagInterpreter: "Coagulation Interpreter",
    coagInterpreterDesc: "Analyze coagulation panels including PT, INR, aPTT, fibrinogen, and D-dimer.",
    rotemInterpreter: "ROTEM Interpreter",
    rotemInterpreterDesc: "Interpret EXTEM, INTEM, FIBTEM, and APTEM viscoelastic assay results.",
    openModule: "Open Module →",
    totalReports: "Total Reports:",
    reportsThisWeek: "Reports This Week:",
    bookmarked: "Bookmarked:",
    
    // cbc page
    cbcAnalyzer: "CBC Analyzer",
    redCellIndices: "Red Cell Indices",
    hgb: "Hgb (g/dL)",
    hct: "Hct (%)",
    rbc: "RBC (×10¹²/L)",
    mcv: "MCV (fL)",
    mch: "MCH (pg)",
    mchc: "MCHC (g/dL)",
    rdw: "RDW (%)",
    whiteCells: "White Cells",
    wbc: "WBC (×10⁹/L)",
    neutrophils: "Neutrophils (×10⁹/L)",
    lymphocytes: "Lymphocytes (×10⁹/L)",
    monocytes: "Monocytes (×10⁹/L)",
    eosinophils: "Eosinophils (×10⁹/L)",
    basophils: "Basophils (×10⁹/L)",
    plateletsHeader: "Platelets",
    plateletsLabel: "Platelets (×10⁹/L)",
    mpv: "MPV (fL)",
    qualitativeFlags: "Qualitative Flags",
    blasts: "Blasts",
    schistocytes: "Schistocytes",
    hypersegPmns: "Hyperseg. PMNs",
    rouleaux: "Rouleaux",
    targetCells: "Target Cells",
    otherFlags: "Other flags",
    otherFlagsPlaceholder: "e.g. polychromasia, teardrop cells",
    analyzeCbc: "Analyze CBC",
    cbcPlaceholderText: "Fill out the form and click Analyze CBC to see the report here.",
    
    // coag page
    coagulationAnalyzer: "Coagulation Analyzer",
    clottingTimes: "Clotting Times",
    pt: "PT (seconds)",
    ptActivity: "PT Activity / Quick (%)",
    inr: "INR",
    aptt: "aPTT (seconds)",
    apttRatio: "aPTT Control Ratio",
    fibrinSystem: "Fibrin System",
    fibrinogen: "Fibrinogen (g/L)",
    thrombinTime: "Thrombin Time (seconds)",
    dDimer: "D-Dimer (mg/L FEU)",
    analyzeCoagulation: "Analyze Coagulation",
    coagPlaceholderText: "Fill out the form and click Analyze Coagulation to see the report here.",
    
    // rotem page
    rotemAnalyzer: "ROTEM Analyzer",
    rotemAssays: "ROTEM Assays",
    rotemCt: "CT (seconds)",
    rotemCft: "CFT (seconds)",
    rotemAlphaAngle: "Alpha Angle (°)",
    rotemMcf: "MCF (mm)",
    rotemLi30: "LI30 (%)",
    analyzeRotem: "Analyze ROTEM",
    rotemPlaceholderText: "Fill out the form and click Analyze ROTEM to see the report here.",
    
    // settings page
    interfaceSettings: "Interface Settings",
    interfaceLanguage: "Interface Language",
    english: "English",
    french: "Français",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    apiConfiguration: "API Configuration",
    apiConnected: "Gemini API Connected",
    apiKeyNotConfigured: "API Key Not Configured",
    apiHelpText: "Enter your Google Gemini API Key below. Keys are stored locally on your device and are only utilized for analyzing diagnostic reports.",
    apiKeyPlaceholder: "Enter Gemini API key…",
    saving: "Saving…",
    saveKey: "Save Key",
    knowledgeBase: "Knowledge Base",
    available: "Available",
    empty: "Empty",
    corpusUpdateText: "To update: replace files in the corpus/ directory and restart the server.",
    about: "About",
    application: "Application",
    version: "Version",
    educationalWarning: "Educational use only. Not for clinical diagnosis.",
    dangerZone: "Danger Zone",
    dangerZoneHelpText: "These actions are destructive and cannot be undone. Please proceed with caution.",
    clearAllReports: "Clear all reports",
    clearAllChats: "Clear all chat sessions",
    clearReportsModalTitle: "Clear All Reports",
    clearReportsModalMessage: "Are you sure you want to soft-delete all saved reports in the database? This action is permanent and cannot be undone.",
    clearChatsModalTitle: "Clear All Chat Sessions",
    clearChatsModalMessage: "Are you sure you want to permanently delete all chat sessions and their message history? This action is permanent and cannot be undone.",
    
    // chat page & workspace
    conversations: "Conversations",
    newChat: "New Chat",
    newSession: "New Session",
    doubleClickToRename: "Double-click to rename",
    deleteSession: "Delete session",
    confirmDeleteSession: "Are you sure you want to delete this session?",
    selectOrCreateSession: "Select or create a conversation session to begin.",
    consultWithHematox: "Consult with HematoX",
    chatWelcomeSub: "Ask complex hematology questions or reference casebook reports using / to receive instant hypotheses.",
    suggestInterpretCbc: "Interpret CBC report",
    suggestInterpretCbcDesc: "Analyze blood parameters for anemia or infection cues.",
    suggestApttPt: "APTT & PT prolongation",
    suggestApttPtDesc: "Explore diagnostic pathways for isolated APTT prolongation.",
    suggestRotem: "ROTEM assay patterns",
    suggestRotemDesc: "Analyze hyperfibrinolysis and clotting factor signature variations.",
    insertReportReference: "Insert Report Reference",
    referenceReports: "Reference Reports",
    noReportsAvailable: "No reports available.",
    chatPlaceholder: "Ask HematoX or type / to attach reports...",
    referencedReports: "Referenced Reports",
    send: "Send",
    
    // casebook page
    select: "Select",
    newAnalysis: "New Analysis",
    searchPlaceholder: "Search reports or patients...",
    selected: "selected",
    referenceToChat: "Reference to Chat",
    bookmarkAll: "Bookmark All",
    deleteSelected: "Delete Selected",
    noReportsFound: "No reports found",
    runAnalysisToSave: "Run an analysis to save your first report.",
    adjustFiltersOrSearch: "Try adjusting your filters or search query.",
    goToDashboard: "Go to Dashboard",
    deleteReportsModalTitle: "Delete Reports?",
    deleteReportsModalMessage: "Are you sure you want to permanently delete the selected reports? This action cannot be undone.",
    backToCasebook: "Back to Casebook",
    copyReport: "Copy Report",
    copied: "Copied",
    exportPdf: "Export PDF",
    exporting: "Exporting...",
    exportMarkdown: "Export Markdown",
    injectIntoChat: "Inject into Chat",
    editReport: "Edit Report",
    cancelEdit: "Cancel Edit",
    delete: "Delete",
    yesDelete: "Yes, Delete",
    reportNotFound: "Report not found.",
    noReportGenerated: "No report generated yet.",
    saveEdits: "Save Edits",
    
    // splash screen
    hematoxPlatform: "HematoX Platform",
    hematologySystem: "Hematology Intelligence System",
  },
  fr: {
    // common/general
    cancel: "Annuler",
    confirm: "Confirmer",
    saveChanges: "Enregistrer les modifications",
    goBack: "Retour",
    areYouSure: "Êtes-vous sûr ?",
    patientLabel: "Patient",
    
    // common/sidebar
    dashboard: "Tableau de bord",
    cbc: "NFS",
    coagulation: "Coagulation",
    rotem: "ROTEM",
    casebook: "Registre de cas",
    chat: "Chat",
    settings: "Paramètres",
    patientName: "Nom du patient (facultatif — pour l'étiquetage du rapport uniquement)",
    patientContext: "Contexte patient",
    age: "Âge",
    sex: "Sexe",
    unspecified: "Non spécifié",
    male: "Homme",
    female: "Femme",
    analyzing: "Analyse en cours...",
    goToSettings: "Aller aux paramètres",
    saveToCasebook: "Enregistrer dans le Registre",
    savedToCasebook: "Enregistré dans le Registre",
    
    // home page / dashboard
    clinicalAnalysis: "Analyse Clinique",
    selectModule: "Sélectionnez un module de diagnostic pour commencer l'interprétation structurée.",
    cbcInterpreter: "Interprète NFS",
    cbcInterpreterDesc: "Interpréter les valeurs de la numération formule sanguine, y compris les indices érythrocytaires, la formule leucocytaire et les paramètres plaquettaires.",
    coagInterpreter: "Interprète Coagulation",
    coagInterpreterDesc: "Analyser les bilans de coagulation, y compris le TP, l'INR, le TCA, le fibrinogène et les D-dimères.",
    rotemInterpreter: "Interprète ROTEM",
    rotemInterpreterDesc: "Interpréter les résultats des tests viscoélastiques EXTEM, INTEM, FIBTEM et APTEM.",
    openModule: "Ouvrir le module →",
    totalReports: "Total des rapports :",
    reportsThisWeek: "Rapports cette semaine :",
    bookmarked: "Favoris :",
    
    // cbc page
    cbcAnalyzer: "Analyseur NFS",
    redCellIndices: "Indices érythrocytaires",
    hgb: "Hb (g/dL)",
    hct: "Hte (%)",
    rbc: "GR (×10¹²/L)",
    mcv: "VGM (fL)",
    mch: "TCMH (pg)",
    mchc: "CCMH (g/dL)",
    rdw: "IDVE (%)",
    whiteCells: "Leucocytes",
    wbc: "GB (×10⁹/L)",
    neutrophils: "Neutrophiles (×10⁹/L)",
    lymphocytes: "Lymphocytes (×10⁹/L)",
    monocytes: "Monocytes (×10⁹/L)",
    eosinophils: "Éosinophiles (×10⁹/L)",
    basophils: "Basophiles (×10⁹/L)",
    plateletsHeader: "Plaquettes",
    plateletsLabel: "Plaquettes (×10⁹/L)",
    mpv: "VPM (fL)",
    qualitativeFlags: "Anomalies qualitatives",
    blasts: "Blastes",
    schistocytes: "Schistocytes",
    hypersegPmns: "PNN hypersegmentés",
    rouleaux: "Rouleaux",
    targetCells: "Target cells (hématies en cible)",
    otherFlags: "Autres anomalies",
    otherFlagsPlaceholder: "ex: polychromatophilie, dacryocytes",
    analyzeCbc: "Analyser la NFS",
    cbcPlaceholderText: "Remplissez le formulaire et cliquez sur Analyser la NFS pour voir le rapport ici.",
    
    // coag page
    coagulationAnalyzer: "Analyseur de coagulation",
    clottingTimes: "Temps de coagulation",
    pt: "TP (secondes)",
    ptActivity: "Activité du TP / Quick (%)",
    inr: "INR",
    aptt: "TCA (secondes)",
    apttRatio: "Ratio TCA (malade/témoin)",
    fibrinSystem: "Système de la fibrine",
    fibrinogen: "Fibrinogène (g/L)",
    thrombinTime: "Temps de thrombine (secondes)",
    dDimer: "D-Dimères (mg/L FEU)",
    analyzeCoagulation: "Analyser la coagulation",
    coagPlaceholderText: "Remplissez le formulaire et cliquez sur Analyser la coagulation pour voir le rapport ici.",
    
    // rotem page
    rotemAnalyzer: "Analyseur ROTEM",
    rotemAssays: "Analyses ROTEM",
    rotemCt: "CT (secondes)",
    rotemCft: "CFT (secondes)",
    rotemAlphaAngle: "Angle Alpha (°)",
    rotemMcf: "MCF (mm)",
    rotemLi30: "LI30 (%)",
    analyzeRotem: "Analyser le ROTEM",
    rotemPlaceholderText: "Remplissez le formulaire et cliquez sur Analyser le ROTEM pour voir le rapport ici.",
    
    // settings page
    interfaceSettings: "Paramètres de l'interface",
    interfaceLanguage: "Langue de l'interface",
    english: "English",
    french: "Français",
    lightMode: "Mode Clair",
    darkMode: "Mode Sombre",
    apiConfiguration: "Configuration de l'API",
    apiConnected: "API Gemini Connectée",
    apiKeyNotConfigured: "Clé API non configurée",
    apiHelpText: "Saisissez votre clé API Google Gemini ci-dessous. Les clés sont stockées localement sur votre appareil et ne sont utilisées que pour analyser les rapports de diagnostic.",
    apiKeyPlaceholder: "Saisir la clé API Gemini...",
    saving: "Enregistrement...",
    saveKey: "Enregistrer la clé",
    knowledgeBase: "Base de connaissances",
    available: "Disponible",
    empty: "Vide",
    corpusUpdateText: "Pour mettre à jour : remplacez les fichiers dans le dossier corpus/ et redémarrez le serveur.",
    about: "À propos",
    application: "Application",
    version: "Version",
    educationalWarning: "Usage pédagogique uniquement. Non destiné au diagnostic clinique.",
    dangerZone: "Zone de danger",
    dangerZoneHelpText: "Ces actions sont destructrices et irréversibles. Veuillez procéder avec prudence.",
    clearAllReports: "Effacer tous les rapports",
    clearAllChats: "Effacer toutes les sessions de chat",
    clearReportsModalTitle: "Effacer tous les rapports",
    clearReportsModalMessage: "Êtes-vous sûr de vouloir supprimer temporairement (soft-delete) tous les rapports enregistrés dans la base de données ? Cette action est définitive et irréversible.",
    clearChatsModalTitle: "Effacer toutes les sessions de chat",
    clearChatsModalMessage: "Êtes-vous sûr de vouloir supprimer définitivement toutes les sessions de chat et leur historique de messages ? Cette action est définitive et irréversible.",
    
    // chat page & workspace
    conversations: "Conversations",
    newChat: "Nouveau chat",
    newSession: "Nouvelle session",
    doubleClickToRename: "Double-cliquez pour renommer",
    deleteSession: "Supprimer la session",
    confirmDeleteSession: "Êtes-vous sûr de vouloir supprimer cette session ?",
    selectOrCreateSession: "Sélectionnez ou créez une session de conversation pour commencer.",
    consultWithHematox: "Consulter avec HematoX",
    chatWelcomeSub: "Posez des questions d'hématologie complexes ou référencez des rapports du registre en utilisant / pour obtenir des hypothèses instantanées.",
    suggestInterpretCbc: "Interpréter le rapport NFS",
    suggestInterpretCbcDesc: "Analyser les paramètres sanguins à la recherche d'indices d'anémie ou d'infection.",
    suggestApttPt: "Allongement TCA et TP",
    suggestApttPtDesc: "Explorer les démarches diagnostiques pour un allongement isolé du TCA.",
    suggestRotem: "Profils d'analyse ROTEM",
    suggestRotemDesc: "Analyser les variations de profils d'hyperfibrinolyse et de facteurs de coagulation.",
    insertReportReference: "Insérer la référence du rapport",
    referenceReports: "Référencer des rapports",
    noReportsAvailable: "Aucun rapport disponible.",
    chatPlaceholder: "Consulter HematoX ou taper / pour attacher les rapports...",
    referencedReports: "Rapports Référencés",
    send: "Envoyer",
    
    // casebook page
    select: "Sélectionner",
    newAnalysis: "Nouvelle analyse",
    searchPlaceholder: "Rechercher des rapports ou des patients...",
    selected: "sélectionné(s)",
    referenceToChat: "Référencer dans le Chat",
    bookmarkAll: "Tout ajouter aux favoris",
    deleteSelected: "Supprimer la sélection",
    noReportsFound: "Aucun rapport trouvé",
    runAnalysisToSave: "Lancez une analyse pour enregistrer votre premier rapport.",
    adjustFiltersOrSearch: "Essayez d'ajuster vos filtres ou votre recherche.",
    goToDashboard: "Aller au tableau de bord",
    deleteReportsModalTitle: "Supprimer les rapports ?",
    deleteReportsModalMessage: "Êtes-vous sûr de vouloir supprimer définitivement les rapports sélectionnés ? Cette action est irréversible.",
    backToCasebook: "Retour au Registre",
    copyReport: "Copier le rapport",
    copied: "Copié",
    exportPdf: "Exporter en PDF",
    exporting: "Exportation...",
    exportMarkdown: "Exporter en Markdown",
    injectIntoChat: "Injecter dans le Chat",
    editReport: "Modifier le rapport",
    cancelEdit: "Annuler les modifications",
    delete: "Supprimer",
    yesDelete: "Oui, supprimer",
    reportNotFound: "Rapport introuvable.",
    noReportGenerated: "Aucun rapport généré pour le moment.",
    saveEdits: "Enregistrer les modifications",
    
    // splash screen
    hematoxPlatform: "Plateforme HematoX",
    hematologySystem: "Système d'Intelligence Hématologique",
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('hematox-language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('hematox-language', language);
  }, [language]);

  const t = (key) => {
    return dictionary[language]?.[key] || dictionary['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
